### ISSUE TITLE
antibody design paper

### ISSUE THREAD

**Issue by pengzhangzhi** [amorehead/awesome-molecular-generation#4]
Hi! This awesome list is great! I would like to add a few papers about antibody design. If you think they are appropriate for this topic, please let me know. I am happy to create a pr.

Best,
Zhangzhi

List of papers published at CS conferences in chronological order
 ICML22, Antibody-Antigen Docking and Design via Hierarchical Structure Refinement  
[[paper](https://proceedings.mlr.press/v162/jin22a/jin22a.pdf)] [[code](https://github.com/wengong-jin/abdockgen)]
NIPS22, Antigen-Specific Antibody Design and Optimization with Diffusion-Based Generative Models for Protein Structures
[[paper](https://openreview.net/forum?id=jSorGn2Tjg)] [[code](https://github.com/luost26/diffab)]
ICLR22,  ITERATIVE REFINEMENT GRAPH NEURAL NETWORK FOR ANTIBODY SEQUENCE-STRUCTURE CO-DESIGN  
[[paper](https://openreview.net/forum?id=LI2bhrE_2A)] [[code](https://github.com/wengong-jin/RefineGNN)]
ICLR23, Conditional Antibody Design as 3D Equivariant Graph Translation 
[[paper](https://openreview.net/pdf?id=LFHFQbjxIiP)] [[code](https://github.com/thunlp-mt/mean)]
ICLR23, Protein Sequence and Structure Co-Design with Equivariant Translation  
[[paper](https://openreview.net/forum?id=pRCMXcfdihq)] 
 preprint, Incorporating Pre-training Paradigm for Antibody Sequence-Structure Co-design

**Comment by amorehead** [comment]
Thanks for your suggestions, @pengzhangzhi! I have added the papers you listed here to the master list. Exciting to now have some ICLR 2023 publications in the list as well!

**Comment by pengzhangzhi** [comment]
Glad to help! haha, the ICLR23 papers are recently open-reviewed. Based on their high scores and positive reviews, I assume they are accepted!
