### ISSUE TITLE
New paper recommend

### ISSUE THREAD

**Issue by hackerchenzhuo** [amorehead/awesome-molecular-generation#6]
Hi, we are the authors of [Mol-Instructions: A Large-Scale Biomolecular Instruction Dataset for Large Language Models](https://arxiv.org/abs/2306.08018).
And  recently we have a new related paper recommendation. Do you think it fits the theme of this project?  😄
- [Domain-Agnostic Molecular Generation with Self-feedback](https://arxiv.org/pdf/2301.11259.pdf) [[project](https://github.com/zjunlp/MolGen)]

**Comment by amorehead** [comment]
Hello. Thanks for this recommendation! I would be happy to add this paper to the list.

Cheers!

**Comment by hackerchenzhuo** [comment]
@amorehead Hi, I apologize for the mistake I made 😂.
In fact, these two papers are different versions of the same paper, with the latter being the latest version:
- [arXiv 2023] Molecular Language Model as Multi-task Generator [[Paper]](https://arxiv.org/abs/2301.11259)[[Code]](https://github.com/zjunlp/MolGen)
- [arXiv 2023] Domain-Agnostic Molecular Generation with Self-feedback [[Paper]](https://arxiv.org/abs/2301.11259)[[Code]](https://github.com/zjunlp/MolGen)

The paper I intended to add is as follows, and I apologize for the confusion in the order:
- [arXiv 2023] [Mol-Instructions: A Large-Scale Biomolecular Instruction Dataset for Large Language Models](https://arxiv.org/abs/2306.08018). [[Code](https://github.com/zjunlp/Mol-Instructions)]

**Comment by amorehead** [comment]
Hi, @hackerchenzhuo. To clarify, were you wanting the Mol-Instructions manuscript or instead the Self-Feedback manuscript to be added?

**Comment by hackerchenzhuo** [comment]
@amorehead Yes, and perhaps you can replace the 'Multi-task Generator' manuscript with the 'Self-Feedback' manuscript because they are actually the same paper. 

Best wish!

**Comment by amorehead** [comment]
Hi, @hackerchenzhuo. I believe the paper list should now reflect these suggestions. Let me know if you have any other comments or feedback. Thanks!

**Comment by hackerchenzhuo** [comment]
That's great! I don't have any more questions, thanks a lot!
Have a nice day!

**Comment by amorehead** [comment]
You as well!
